# Generated by Django 5.0.1 on 2024-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_assignment_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start',
            field=models.DateField(),
        ),
    ]
