# Generated by Django 5.0.1 on 2024-01-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacher_course_course_teacher'),
        ('teacher', '0006_alter_attendance_course_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('teacher', 'course_class', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_student',
            field=models.ManyToManyField(related_name='attendance', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.teacher'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
