# Generated by Django 5.0.1 on 2024-01-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacher_course_course_teacher'),
        ('teacher', '0007_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
            preserve_default=False,
        ),
    ]
