# Generated by Django 5.0 on 2024-01-30 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
