# Generated by Django 5.0 on 2024-02-05 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_rename_parent_name_parent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='libraryBook',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('availability_status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('borrowing_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
                ('borrowed_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.librarybook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
