# Generated by Django 5.0 on 2024-02-06 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_borrowing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
    ]
