# Generated by Django 5.0 on 2024-02-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_receipt_receipt_number_fee_created_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
