# Generated by Django 5.0 on 2024-02-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_role_role_staff'),
        ('staff', '0010_delete_receipt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('student', 'fee')},
        ),
    ]
