# Generated by Django 5.0 on 2024-02-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_borrowing_due_date_exam_result_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
