# Generated by Django 5.0 on 2024-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], default='Student', max_length=50),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
