# Generated by Django 5.0 on 2024-01-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_schooluser_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
