# Generated by Django 5.0.1 on 2024-01-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'grade', 'teacher')},
        ),
    ]
