# Generated by Django 5.0 on 2024-01-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_user',
            new_name='student_user',
        ),
    ]
