# Generated by Django 5.0.1 on 2024-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_parent_email_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
