# Generated by Django 5.0.1 on 2024-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teacher_address_teacher_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(),
        ),
    ]
