# Generated by Django 5.0.1 on 2024-02-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacher_address_alter_teacher_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_name',
            new_name='name',
        ),
    ]
