# Generated by Django 5.0.1 on 2024-01-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submit',
            options={'verbose_name': 'Submission'},
        ),
        migrations.AddField(
            model_name='submit',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submit',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
