# Generated by Django 5.0 on 2024-01-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submit',
            options={'verbose_name': 'Submission'},
        ),
    ]
