# Generated by Django 5.0 on 2024-01-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_submit_options'),
        ('student', '0002_alter_submit_options_submit_checked_submit_feedback'),
    ]

    operations = [
    ]
