# Generated by Django 5.0 on 2024-02-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_merge_20240125_1951'),
        ('teacher', '0011_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='teacher.assignment'),
        ),
    ]
