# Generated by Django 5.0 on 2024-01-11 14:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('course_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentStudent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_absent', models.BooleanField(default=True)),
                ('absentee', models.ManyToManyField(to='accounts.student')),
                ('sub_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_class.timetable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
