# Generated by Django 5.0.1 on 2024-01-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='work',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='fk_work',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
    ]
