# Generated by Django 5.0 on 2024-01-11 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_submit_sb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='hw_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
